#
# |  \/  |           | |               | |
# | \  / | __ _ _ __ | |__  _   _ _ __ | |_
# | |\/| |/ _` | '_ \| '_ \| | | | '_ \| __|
# | |  | | (_| | | | | | | | |_| | | | | |_
# |_|  |_|\__,_|_| |_|_| |_|\__,_|_| |_|\__|

# MESSAGE PLACEHOLDERS:
# %player%: Player's name
# %message%: Chat message by player
# %default%: Default teamchat message
#
# COLOR CODES:
# You can find a list of color codes at the link below
# https://minecraft.gamepedia.com/Formatting_codes
#
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  +        Settings          +
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# If true, it will heal all players on start of a hunt
healStart: true

# If true, it will feed all players on start of a hunt
feedStart: true

# If true, it will make the time day on start of a hunt
dayStart: true

# If true, it will clear all participant's inventories on start of a hunt
clearStart: true

# If set to true, all players will reset achievements on start
achievementReset: true

# Random Wild Teleporting is not included in 1.1 unfortunately, it's a pain to do and will be postponed.
# Setting it to true or false wont do anything, functionality will be added in later versions.

# **EXPERIMENTAL**
# If you don't want to be in the same spawn point and calculate your next spawn for a manhunt game, let the plugin calculate a safe spot.
# Even if in experimental stage, it's absolutely recommended to set this to true if you wanna be slack.
#randomWildTeleportStart: false

# This feature will come out in the future
# For now, you are limited to 15000 x and z bounds.

# Spawn calculator will not attempt to go above 10,000 X/Z (or any number you set it to), which means it will have bounds.
# You can set this to a very relatively high number, but for default it's gonna be 10K.
#boundXcoordinate: 10000
#boundZcoordinate: 10000

#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  +     Manhunt Settings     +
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# If set to true, compass will have a counter of blocks displayed
# between you and your target
distanceTracker: true

# Change this to see how teamchat looks in game. Placeholders listed above
# Set to "%default%" to get the default teamchat message

# Hunter Team Chat
hunterTeamchatMessage: "&c&l[Hunter Chat] &c%player%: &6&l%message%"

## Runner Team Chat
#runnerTeamchatMessage: "&a&l[Runner Chat] &a%player%: &b&l%message%"


# If you want to spice up your game
# If true, runner will get a compass pointing to the closest nether fortress
fortressTracker: false


# Plays when a manhunt starts with a headstart. Set to a minecraft sound for no error
startSound: "ENTITY_ENDER_DRAGON_GROWL"

# Particle effect for when a runner dies. Only activates in a two or more runner game. Set to "NONE" for no particles
particleEffect: "EXPLOSION_NORMAL"

#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  +     Discord Settings     +
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# If true, discord integration will be enabled
discordIntegration: false

# Paste your bot's token here for it to work
botToken: "0000000000"

# Set this to your bot's status (Ex: "Watching <bot-activity-message>")
botActivityMessage: "A Manhunt bot"

# Set to true for people in minecraft to talk to people in discord
discordMcChat: false

# If disc-mc-chat is true, put ID of selected text channel for people to talk in
# Leave this untouched if the above is false
discordMcChannel: "0000000000"

