#
# |  \/  |           | |               | |
# | \  / | __ _ _ __ | |__  _   _ _ __ | |_
# | |\/| |/ _` | '_ \| '_ \| | | | '_ \| __|
# | |  | | (_| | | | | | | | |_| | | | | |_
# |_|  |_|\__,_|_| |_|_| |_|\__,_|_| |_|\__|

# MESSAGE PLACEHOLDERS:
# %player%: Player's name
# %message%: Chat message by player
# %default%: Default teamchat message
#
# COLOR CODES:
# You can find a list of color codes at the link below
# https://minecraft.gamepedia.com/Formatting_codes
#
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  +        Settings          +
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# If true, it will heal all players on start of a hunt
healStart: true

# If true, it will feed all players on start of a hunt
feedStart: true

# If true, it will make the time day on start of a hunt
dayStart: true

# If true, it will clear all participant's inventories on start of a hunt
clearStart: true

# If set to true, all players will reset achievements on start
achievementReset: true

#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  +     Manhunt Settings     +
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# If set to true, compass will have a counter of blocks displayed
# between you and your target
distanceTracker: true

# Change this to see how teamchat looks in game. Placeholders listed above
# Set to "%default%" to get the default teamchat message

# Hunter Team Chat
hunterTeamchatMessage: "&c&l[Hunter Chat] &c%player%: &6&l%message%"

# Runner Team Chat
runnerTeamchatMessage: "&a&l[Runner Chat] &a%player%: &b&l%message%"

# Default prefix before every message to turn it into a teamchat message
teamchatPrefix: "#"


# If you want to spice up your game
# If true, runner will get a compass pointing to the closest nether fortress
fortressTracker: false

# YOU DON'T HAVE TO PLAY below 1.16.2 anymore! The rate of the pearls will be boosted like in 1.16.1
# Boosts percentage chance of piglins trading ender pearls
piglinPearlBoost: false


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# +     Advanced Settings     +
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Plays when a manhunt begins with a head-start. Set to a valid minecraft sound
startSound: "ENTITY_WITHER_DEATH"

# Particle effect for when a runner dies. Only activates in a two or more runner game. Set to "NONE" for no particles
particleEffect: "EXPLOSION_NORMAL"

#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  +     Discord Settings     +
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# If true, discord integration will be enabled
discordIntegration: false

# Paste your bot's token here for it to work
botToken: "0000000000"

# Set this to your bot's status (Ex: "Watching <bot-activity-message>")
botActivityMessage: "A Manhunt bot"

# Set to true for people in minecraft to talk to people in discord
discordMcChat: false

# If disc-mc-chat is true, put ID of selected text channel for people to talk in
# Leave this untouched if the above is false
discordMcChannel: "0000000000"

